manage_syllabus_app/controllers.py
import math
import os

from manage_syllabus_app import app, dao, login
import functools
from flask import render_template, request, url_for, flash, jsonify, abort, Blueprint
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.utils import redirect
from manage_syllabus_app import db

from manage_syllabus_app.models import Faculty, Lecturer, Credit, Subject, Syllabus, RequirementSubject, \
    TypeRequirement, MainSection, LearningMaterial, TypeLearningMaterial, TextSubSection, \
    CourseLearningOutcome, CourseObjective, SelectionSubSection, AttributeValue, ProgrammeLearningOutcome, \
    CloPloAssociation, User, UserRole
from manage_syllabus_app.services import build_mock_syllabus_from_json

api = Blueprint('api', __name__, url_prefix='/api')


def to_roman(n):
    """Chuyển một số nguyên sang số La Mã."""
    if not isinstance(n, int) or not 1 <= n < 4000:
        return n  # Trả về giá trị gốc nếu không phải là số hợp lệ
    val = [
        1000, 900, 500, 400,
        100, 90, 50, 40,
        10, 9, 5, 4,
        1
    ]
    syb = [
        "M", "CM", "D", "CD",
        "C", "XC", "L", "XL",
        "X", "IX", "V", "IV",
        "I"
    ]
    roman_num = ''
    i = 0
    while n > 0:
        for _ in range(n // val[i]):
            roman_num += syb[i]
            n -= val[i]
        i += 1
    return roman_num



# CÁC ROUTE GỐC
@app.route('/')
def index():
    page_size = app.config["PAGE_SIZE"]
    total = dao.count_syllabuses()
    page = request.args.get('page', 1, type=int)
    syllabus = []
    if current_user.is_authenticated:
        if current_user.user_role == UserRole.ADMIN:
            # Đếm tất cả
            total = dao.count_syllabuses()
            # Lấy dữ liệu trang hiện tại
            syllabus = dao.get_all_syllabuses(page=page, page_size=page_size)

        elif current_user.user_role == UserRole.USER and current_user.lecturer_id:
            # Đếm theo giảng viên
            total = dao.count_syllabuses(lecturer_id=current_user.lecturer_id)
            # Lấy dữ liệu trang hiện tại
            syllabus = dao.get_syllabuses_by_lecturer_id(lecturer_id=current_user.lecturer_id,
                                                         page=page, page_size=page_size)
    all_faculties = dao.get_all_faculties()
    return render_template('index.html', syllabuses=syllabus, all_faculties=all_faculties,
                           pages=math.ceil(total / page_size))


@app.route('/editor')
@login_required
def editor():
    return render_template('editor.html')


@app.route('/specialist')
@login_required
def specialist_view():
    if current_user.user_role != UserRole.SPECIALIST:
        abort(403)
    template_files = []

    return render_template('specialist/index.html', template_files=template_files)

@app.route('/specialist/template/<filename>')
@login_required
def specialist_template_detail(filename):
    # 1. Kiểm tra quyền
    if current_user.user_role != UserRole.SPECIALIST:
        abort(403)


    # 3. Gọi hàm xử lý logic
    try:
        mock_syllabus = []
    except ValueError as e:
        flash(str(e), "danger")
        return redirect(url_for('specialist_view'))

    return render_template(
        'specialist/sample_syllabus_view.html',
        syllabus=mock_syllabus,
        is_sample=True,
        all_faculties=[], all_lecturers=[], learning_materials=[],
        all_subjects=[], all_type_subjects=[], plos=[]
    )

@app.route('/syllabus/<int:syllabus_id>/')
@login_required
def syllabus_detail(syllabus_id):
    syllabus = dao.get_syllabus_by_id(syllabus_id)
    all_faculties = dao.get_all_faculties()
    all_lecturers = dao.get_lecturers()
    all_type_subjects = dao.get_all_type_subjects()
    learning_materials = dao.get_all_learning_material_types()
    available_subjects = dao.get_available_require_subjects(syllabus.subject.id)
    plos = dao.get_all_plos()
    sorted_plos = dao.get_sorted_plos_for_syllabus(syllabus_id)
    return render_template('syllabus_detail.html', syllabus=syllabus,
                           all_faculties=all_faculties, all_lecturers=all_lecturers,
                           learning_materials=learning_materials,
                           all_type_subjects=all_type_subjects, all_subjects=available_subjects, plos=plos,
                           unique_plos=sorted_plos)


@app.context_processor
def util():
    def set_param(**kwargs):
        args = request.args.to_dict()
        args.update(kwargs)
        return url_for('.index', **args)

    return dict(set_param=set_param)


@api.route('/faculties/<int:faculty_id>/lecturers', methods=['GET'])
def get_lecturers_by_faculty(faculty_id):
    lecturers = Lecturer.query.filter_by(faculty_id=faculty_id).all()
    # Trả về list object đơn giản
    return jsonify([{'id': l.id, 'name': l.name} for l in lecturers])


# CÁC ROUTE XÁC THỰC
@app.route('/login', methods=['GET', 'POST'])
def user_login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = dao.get_user_by_username(username)

        if user and dao.check_password(user, password):
            login_user(user=user)
        else:
            flash('Tên đăng nhập hoặc mật khẩu không chính xác!', 'danger')

        if user.user_role == UserRole.SPECIALIST:
            return redirect('/specialist')
        return redirect('/')
    return render_template('login.html')


@app.route('/register', methods=['GET', 'POST'])
def user_register():
    err_msg = ""
    if request.method == 'POST':
        name = request.form.get('name')
        username = request.form.get('username')
        password = request.form.get('password')
        confirm = request.form.get('confirm')

        if password != confirm:
            err_msg = "Mật khẩu xác nhận không khớp!"
        else:
            try:
                dao.add_user(name=name, username=username, password=password)
                return redirect(url_for('user_login'))
            except Exception as e:
                err_msg = "Đã có lỗi xảy ra: " + str(e)

    return render_template('register.html', err_msg=err_msg)


@app.route('/logout')
def user_logout():
    logout_user()
    return redirect(url_for('user_login'))


@app.route('/admin-login', methods=['POST'])
def admin_login():
    username = request.form['username']
    password = request.form['password']
    user = dao.get_user_by_username(username)
    if user and dao.check_password(user, password):
        login_user(user=user)
    else:
        flash('Tên đăng nhập hoặc mật khẩu không chính xác!', 'danger')
    return redirect('/admin')


@api.route('/syllabuses/<int:syllabus_id>/director', methods=['PATCH'])
@login_required
def update_syllabus_director(syllabus_id):
    syllabus = db.session.get(Syllabus, syllabus_id)
    if not syllabus:
        flash('Không tìm thấy đề cương', 'danger')
        return redirect(url_for('index'))

    data = request.get_json()
    if not data:
        abort(400, description="Không có dữ liệu đầu vào (Yêu cầu phải là JSON).")

    try:
        # 1. Cập nhật Syllabus
        if 'faculty_id' in data:
            syllabus.faculty_id = int(data['faculty_id'])
        if 'lecturer_id' in data:
            syllabus.lecturer_id = int(data['lecturer_id'])

        # 2. Cập nhật Lecturer (nếu có thông tin)
        lecturer_to_update = db.session.get(Lecturer, syllabus.lecturer_id)
        if lecturer_to_update:
            if 'lecturer_email' in data:
                lecturer_to_update.email = data['lecturer_email']
            if 'lecturer_room' in data:
                lecturer_to_update.room = data['lecturer_room']

        db.session.commit()

        # Trả về thông tin giảng viên đã được cập nhật
        return jsonify(lecturer_to_update.to_dict())

    except Exception as e:
        db.session.rollback()
        return jsonify(success=False, message=f"Lỗi khi cập nhật CSDL: {str(e)}"), 500


@api.route('/text-subsections/<int:subsection_id>', methods=['PATCH'])
def update_text_subsection(subsection_id):
    subsection = db.session.get(TextSubSection, subsection_id)
    if not subsection:
        abort(404, description="Không tìm thấy tiểu mục văn bản này.")
    data = request.get_json()
    if not data or 'content' not in data:
        abort(400, description="Yêu cầu phải là JSON và chứa trường 'content'.")
    subsection.content = data.get('content')
    try:
        db.session.commit()
        return jsonify(subsection.to_dict())
    except Exception as e:
        db.session.rollback()
        return jsonify(success=False, message=f"Lỗi khi cập nhật CSDL: {str(e)}"), 500


@api.route('/subjects/<string:subject_id>', methods=['PATCH'])
@login_required
def update_subject(subject_id):
    subject = dao.get_subject_by_id(subject_id)
    if not subject:
        abort(404, description="Không tìm thấy môn học.")

    data = request.get_json()
    if not data:
        abort(400, description="Không có dữ liệu đầu vào (Yêu cầu phải là JSON).")

    # Cập nhật các trường được phép
    if 'name' in data:
        subject.name = data['name']

    try:
        db.session.commit()
        # Trả về tài nguyên đã được cập nhật (dùng hàm .to_dict() mới)
        return jsonify(subject.to_dict())
    except Exception as e:
        db.session.rollback()
        return jsonify(success=False, message=f"Lỗi khi cập nhật CSDL: {str(e)}"), 500


@api.route('/credits/<int:credit_id>', methods=['PATCH'])
def update_credit(credit_id):
    credit = dao.get_credit_by_id(credit_id)

    if not credit:
        abort(404, description="Không tìm thấy tín chỉ")

    data = request.get_json()

    if 'numberTheory' in data:
        credit.numberTheory = data.get('numberTheory')
    if 'numberPractice' in data:
        credit.numberPractice = data.get('numberPractice')
    if 'hourSelfStudy' in data:
        credit.hourSelfStudy = data.get('hourSelfStudy')

    try:
        db.session.commit()

manage_syllabus_app/templates/partials/_course_overview.html
<div class="mb-5">
    {% from 'partials/_macros.html' import editable_section_header %}

    <h3 class="section-title-fresh mb-3">
            <i class="fas fa-info-circle me-2"></i>{{part.position | roman}}. {{ part.name }}
    </h3>
    <table class="table align-middle info-table-fresh">
        <tbody>
        {% for sub_item in part.sub_sections %}
        {% with item_index = loop.index %}
        {% include 'partials/subsections/_' + sub_item.type + '.html' %}
        {% endwith %}
        {% endfor %}
        </tbody>
    </table>
</div>

manage_syllabus_app/templates/partials/_general_info.html
<div class="mb-5">
    {% from 'partials/_macros.html' import editable_section_header %}
    {% from 'partials/_macros.html' import editable_field %}
    <h3 class="section-title-fresh mb-3">
            <i class="fas fa-info-circle me-2"></i>{{part.position | roman}}. {{ part.name }}
    </h3>
    <table class="table align-middle info-table-fresh">
        <tbody>
        {# 1. Tên môn học tiếng Việt #}
        <tr>
            <th scope="row" class="fs-6">1. Tên môn học tiếng Việt/Course title in Vietnamese</th>
            <td>
                {{editable_field(syllabus.subject, 'name','Subject', syllabus, input_type='input', data_rest_url=url_for('api.update_subject', subject_id=syllabus.subject.id))}}
            </td>
        </tr>

        {# Mã môn học #}
        <tr>
            <th scope="row" class="fs-6">Mã môn học/Course code</th>
            <td>
                {{syllabus.subject.id}}
            </td>
        </tr>

        {# Các tiểu mục còn lại #}
        {% for sub_item in part.sub_sections %}
        {% with item_index = loop.index + 1 %}
        {% include 'partials/subsections/_' + sub_item.type + '.html' %}
        {% endwith %}
        {% endfor %}
        </tbody>
    </table>
</div>

manage_syllabus_app/templates/partials/_macros.html
{% macro editable_field(object, field_name, model_name, syllabus_object, input_type='input', data_rest_url=None) %}
<div id="editable-container-{{ model_name }}-{{ object.id }}-{{ field_name }}" class="editable-container">
    <div class="display-view mt-5">
        <p class="mb-0" style="white-space: pre-wrap;">{{ object[field_name] or "Chưa có nội dung"}}</p>
        <button type="button" class="btn btn-outline-primary btn-sm ms-3 flex-shrink-0 edit-trigger-button"
                onclick="toggleFieldEdit('{{ model_name }}-{{ object.id }}-{{ field_name }}', true)">
            <i class="fas fa-pencil-alt"></i> Chỉnh sửa
        </button>
    </div>

    <div class="edit-view" style="display: none;">
        <form
              class="{{ 'rest-form' if data_rest_url else 'ajax-form' }}"
              data-method="{{ 'PATCH' if data_rest_url else 'POST' }}"
              data-url="{{ data_rest_url }}"
              action='#' >

            {# Các trường ẩn này vẫn cần thiết để JavaScript (cả cũ và mới) có thể hoạt động #}
            <input type="hidden" name="model_name" value="{{ model_name }}">
            <input type="hidden" name="object_id" value="{{ object.id }}">
            <input type="hidden" name="syllabus_id" value="{{ syllabus_object.id }}">

            {% if input_type == 'textarea' %}
            <textarea class="form-control input-style" name="{{ field_name }}" rows="3">{{ object[field_name] }}</textarea>
            {% else %}
            <input type="text" class="form-control input-style" name="{{ field_name }}" value="{{ object[field_name] }}">
            {% endif %}

            <div class="text-end mt-2">
                <button type="button" class="btn btn-secondary btn-sm"
                        onclick="toggleFieldEdit('{{ model_name }}-{{ object.id }}-{{ field_name }}', false)">Hủy
                </button>
                <button type="submit" class="btn btn-success btn-sm">Lưu</button>
            </div>
        </form>
    </div>
</div>
{% endmacro %}